[font]
size = 10

[font.normal]
family = "MonaspiceRn Nerd Font"

[window]
padding = { x = 6, y = 4}

[colors.primary]
background = "#362e45"
##00242d
##0D1926
foreground = "#FFCCDD"

[cursor]
style = { shape = "Underline", blinking = "Never" }
