font_family      ZedMono Nerd Font
font_size        11
disable_ligatures never
background  #121019
#121019
#0e0f10
#22112a
#221727
#2a1d31
#121124
#0f0f1a
#201a2f
foreground #eee9ff
#eee9ff
#ffeef2
#dffff8
#ff91c3
#ff338f
#c79eff
#98e4a7
color0  #121019
color1  #ff338f
color2  #98e4a7
color3  #ff91c3
color4  #c79eff
color5  #ff91c3
color6  #dffff8
color7  #eee9ff
color8  #2a1d31
color9  #ff338f
color10 #98e4a7
color11 #ffeef2
color12 #c79eff
color13 #ff91c3
color14 #dffff8
color15 #ffeef2
cursor  #eee9ff
cursor_shape          underline
cursor_blink_interval 0
shell_integration   enabled no-cursor

window_padding_width 2
background_opacity    1

tab_bar_edge        top
tab_bar_style       fade
tab_bar_align       left
tab_title_template  "{title[:15]}"

active_tab_foreground    #221727
active_tab_background #c79eff
inactive_tab_foreground  #eee9ff
inactive_tab_background  #121019
tab_bar_margin_width     0
tab_bar_min_tabs         2

copy_on_select      clipboard
strip_trailing_spaces smart

repaint_delay       6
input_delay         1
sync_to_monitor     yes

allow_remote_control    socket-only
listen_on               unix:/tmp/kitty-socket

map ctrl+backspace send_text all \x17
map alt+backspace send_text all \x15
# Kitty passes these keys through by default.
# map ctrl+c send_text all \x03
# map ctrl+v send_key ctrl+v
map ctrl+t       new_tab_with_cwd

map ctrl+shift+e no_op
map ctrl+shift+b no_op

map ctrl+1       goto_tab 1
map ctrl+2       goto_tab 2
map ctrl+3       goto_tab 3
map ctrl+4       goto_tab 4
map ctrl+5       goto_tab 5
map ctrl+6       goto_tab 6
map ctrl+7       goto_tab 7
map ctrl+8       goto_tab 8
map ctrl+9       goto_tab 9
