[indicator]
preview = {}
current = { fg = "#0f0f1a", bg = "#eee9ff" }
parent = { fg = "#0f0f1a", bg = "#eee9ff" }

[mgr]
cwd = { fg = "#0f0f1a", bg = "#0f0f1a" }

[pick]
border = { fg = "#c79eff" }

[pick.active]
fg = "#eee9ff"
bg = "#0f0f1a"

[pick.inactive]
fg = "#eee9ff"

[input]
border = { fg = "#c79eff" }
title = { fg = "#eee9ff" }
value = { fg = "#eee9ff" }
selected = { reversed = true }

[confirm]
border = { fg = "#c79eff" }
title = { fg = "#eee9ff" }
body = { fg = "#eee9ff" }
list = { fg = "#eee9ff" }
btn_yes = { reversed = true }
btn_no = { fg = "#eee9ff" }
