[mgr]
show_hidden = true
linemode = "size"

[opener]
opencode = [
  { run = "kitty @ launch --type=tab -- zsh -c 'cd -- \"$1\" && opencode2' zsh %s1", desc = "Opencode" },
]

nvim_file = [{ run = 'nvim %s', block = true, desc = "Nvim" }]

nvim = [
  { run = "kitty @ launch --type=tab -- zsh -c 'cd -- \"$1\" && nvim' zsh %s1", desc = "Nvim" },
]

code = [{ run = "zsh -c 'cd -- \"$1\" && codium .' zsh %s1", desc = "Code" }]

terminal = [{ run = 'kitty @ launch --type=tab --cwd=%s1', desc = "Kitty" }]

finder = [
  { run = 'open -R %s', for = "macos", desc = "Finder" },
  { run = 'xdg-open %d1', for = "linux", desc = "Finder" },
]

pdf = [{ run = 'vivaldi %s', orphan = true, for = "linux", desc = "Vivaldi" }]

[open]
prepend_rules = [{ mime = "application/pdf", use = ["pdf", "open"] }]

rules = [
  { url = "*", use = [
    "nvim_file",
  ] },
  { url = "*/", use = [
    "opencode",
    "nvim",
    "code",
    "terminal",
    "finder",
  ] },
]
