[mgr]
show_hidden = true
linemode = "size"

[opener]
opencode = [
  { run = 'kitty @ launch --type=tab -- zsh -c "cd \"$@\" && opencode"', desc = "Opencode" },
]

nvim_file = [{ run = 'nvim "$@"', block = true, desc = "Nvim" }]

nvim = [
  { run = 'kitty @ launch --type=tab -- zsh -c "cd \"$@\" && nvim"', desc = "Nvim" },
]

codium = [
  { run = 'open -a "VSCodium" "$@"', for = "macos", desc = "Code" },
  { run = 'zsh -c "cd \"$1\" && codium ." -- "$@"', for = "linux", desc = "Code" },
]

terminal = [{ run = 'kitty @ launch --type=tab --cwd="$@"', desc = "Kitty" }]

finder = [
  { run = 'open -R "$@"', for = "macos", desc = "Finder" },
  { run = 'xdg-open "$(dirname "$@")"', for = "linux", desc = "Finder" },
]

[open]
rules = [
  { url = "*", use = [
    "nvim_file",
  ] },
  { url = "*/", use = [
    "opencode",
    "nvim",
    "codium",
    "terminal",
    "finder",
  ] },
]
