gui:
  sidePanelWidth: 0.38
  mainPanelSplitMode: horizontal
  splitDiff: auto
  nerdFontsVersion: "3"
  showNumstatInFilesView: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true
quitOnTopLevelReturn: true

git:
  autoRefresh: true
  autoStageResolvedConflicts: true
  log:
    showGraph: always
    order: topo-order

os:
  editPreset: "nvim"
