gui:
  sidePanelWidth: 0.38
  mainPanelSplitMode: horizontal
  splitDiff: auto
  nerdFontsVersion: "3"
  showNumstatInFilesView: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true
  theme:
    activeBorderColor: ["#c79eff", bold]
    inactiveBorderColor: ["#2a1d31"]
    searchingActiveBorderColor: ["#ff91c3", bold]
    optionsTextColor: ["#c79eff"]
    selectedLineBgColor: ["#201a2f"]
    selectedRangeBgColor: ["#2a1d31"]
    cherryPickedCommitFgColor: ["#121019"]
    cherryPickedCommitBgColor: ["#ff91c3"]
    markedBaseCommitFgColor: ["#121019"]
    markedBaseCommitBgColor: ["#98e4a7"]
    unstagedChangesColor: ["#ff338f"]
    defaultFgColor: ["#eee9ff"]
quitOnTopLevelReturn: true

git:
  autoRefresh: true
  autoStageResolvedConflicts: true
  log:
    showGraph: always
    order: topo-order

os:
  editPreset: "nvim"
