return {
  "xiyaowong/transparent.nvim",
  lazy = false,
  opts = {
    extra_groups = {
      "BufferLineBackground",
      "BufferLineBufferSelected",
      "BufferLineBufferVisible",
      "BufferLineFill",
      "BufferLineIndicatorSelected",
      "BufferLineSeparator",
      "BufferLineSeparatorSelected",
      "BufferLineSeparatorVisible",
      "FloatBorder",
      "NeoTreeNormal",
      "NeoTreeNormalNC",
      "NormalFloat",
      "SignColumn",
      "StatusLine",
      "StatusLineNC",
      "TabLine",
      "TabLineFill",
      "TabLineSel",
      "TelescopeBorder",
      "TelescopeNormal",
      "WinSeparator",
    },
  },
}
